### ISSUE TITLE
Updating Gems Is Extremely Slow

### ISSUE THREAD

**Issue by eonflare** [geminabox/geminabox#70]
Hi Tom,

We've been using Geminabox at my company for awhile now, and first and for most thanks for putting this out there.  It has been incredibly helpful.

Our issue however is that gems seem to not appear to be properly indexed upon loading them with the gem inabox command.  They show up on the page, and they even show up when one does gem search $NAME --source=http://private.server --both.

However, gem install $NAME always fails unless we hit the reindex URL on the private server.  However over time that indexing has become slower and slower, to the point where we can't increase the timeout anymore on the request to allow it to succeed (it's currently at 2 minutes).

I tried setting incremental updates to true to see if that would help.  Our config.ru looks like this:
```
require "rubygems"
require "geminabox"

Geminabox.data = "/var/www/geminabox/data" # …or wherever
Geminabox.configure do |config|
  config.set(:incremental_updates, true)
end

run Geminabox
```

But it seems to not help at all.  Any ideas as to what could be wrong?  We are currently hosting 789 gems on our gem server.

**Comment by ginty** [comment]
To whomever it may help...

On the latest version of Geminabox at the time of writing (0.13.9), I have also come across this issue of excessively slow backend updates causing various timeout issues on the front end clients.
I have not been able to fix this by enabling `incremental_updates` as suggested in this thread, and from looking at the source that would never help the situation for deletes anyway.
Btw, this issue turned out to be caused by the backend delete process taking excessively long: https://github.com/geminabox/geminabox/issues/218

Anyway, sorry I don't have time to turn this into something more official, but there is a relatively easy hack you can do locally to make the reindexing processes (which is taking all the time here) into an offline activity.

I added this modification to `lib/geminabox/server.rb`:

~~~ruby
def reindex(force_rebuild = false)
  # START OF EDIT
  unless force_rebuild == :offline
    # Create a file in the reindex_requests directory, this will be monitored by a cron
    # job and the presence of a file in this dir will trigger an off-line re-index
    require 'fileutils'
    FileUtils.mkdir_p 'reindex_requests'
    system "touch reindex_requests/#{Time.now.to_i}"
    return
  end
  # END OF EDIT

  # Existing method implementation here...
~~~

So it will create a file in a directory whenever a gem is added or removed, returning to the web app or gem command line client straight away.

I then have this script executed via Cron every minute (and with a --force version every hour) to trigger an offline reindex:

~~~ruby
def _reindex_geminabox
  require 'geminabox'

  Geminabox.data = './data'
  Geminabox.build_legacy = false
  Geminabox.rubygems_proxy = false
  Geminabox.allow_remote_failure = false

  start = Time.now
  Geminabox::Server.reindex(:offline)
  duration = (Time.now - start).to_i
  puts
  puts "Reindexing took: #{duration / 60} minutes and #{duration % 60} seconds"
end

if ARGV[0] == "--force"
  _reindex_geminabox
else
  require 'fileutils'
  f = Dir.glob("reindex_requests/*").first
  if f
    FileUtils.rm_f(f)
    _reindex_geminabox
  end
end
~~~

That seems to be working well for us so far and should hopefully allow us to go on and scale well past 1500 gems.
The only downside is that users need to be aware that they need to wait a few minutes before a newly pushed gem is available from the server.
